### ISSUE TITLE
scad files errors

### ISSUE THREAD

**Issue by 111OCT111** [AxMod3DPrint/FB2020#2]
Hi, first of all, thanks for your effort e for making the whole thing parametrized.
I´m trying to change the left_bed_holder_clamp and right to use lm10uu bearings and 10mm rods. 
I´m trying to accomplish using the left_bed_holder_clamp.scad file, I´ve downloaded culain's files referenced on that scad file, replaced the original import file path with my local file path (/mnt/genesis/Documents/STLs/FuseBox1.3_2020/files/Left_Bed_Holder_NEW.stl), but I´m not getting very far with this. Can you give some pointers as how to?
Thanks

**Comment by ViperWorx** [comment]
That file was, er, cobbled together, as such it's not really ideal to edit. I'm going to be working on that conversion, and doing it properly in FreeCad, redesigning the part and doing it properly. 

However, I've just pushed the files again. The reference file is where it should be and is fully manifold. Just clone (probably better for keeping commits updated)/download the repo and the files will be in the correct location. Any STL referenced, should be in the same folder as the SCAD file.

**Comment by ViperWorx** [comment]
Just as a note, there is now a Bed holder test file in the test files folder to use 12mm Rods and bearings.

**Comment by 111OCT111** [comment]
great, thank you for your feedback.

**Comment by ViperWorx** [comment]
Not a problem. If you still want to use 10mm Rods, issue a pull request with your modified files and I'll take a look.
