### ISSUE TITLE
Question: Is it "stable"?

### ISSUE THREAD

**Issue by Nredor** [AxMod3DPrint/FB2020#9]
Is the master branch currently in such state that I could use the parts to print and assemble FB2020+ or is it still work in progress?

**Comment by ViperWorx** [comment]
Yup, all the main parts are not changing, at this point I'm making no major changes as the design works about as well as it can. I've run probably 4-5000 hours without much of an issue at all over 2 FB2020s with a 3rd having just joined my farm.

There may be small changes to superfluous parts like the spool holder I've just swapped out or small additions like a electronics enclosure for the Re-Arm (which I'm going to recommend as an upgrade from the Mega2560), I'm going to start recommending 24v electronics (which requires a slight mod to the RAMPS) and a silicone 240v/110v (depending on your location) heater and aluminium plate, but other than that there's really nothing that's going to change, the base design is there and works.
